### PR TITLE
challenge-0 move initial commands to match text & js version

### PR DESCRIPTION
**Pull request by t3h2mas**
Swaps `yarn run` and `yarn deploy` to match the text description as well as the javascript challenge version

### CODE REVIEW

**Review by grothem — COMMENTED** [review]
Thanks for the PR. We actually need to run `yarn deploy` before running `yarn start`. If you don't deploy the contracts first, the app will fail to build because the contract types won't be generated. I see what you mean about the text though, we should update that to match the commands.

**Comment by t3h2mas** [comment]
Should the JavaScript version be updated to start in the order you specified here?

https://speedrunethereum.com/challenge/simple-nft-example

**Comment by grothem** [comment]
Sorry for the delayed response on this. No the JS repo is ok. The TS version requires the contract types to be generated so there's not compile errors related to the contract typings

**Comment by mojalil** [comment]
is it worth updating the instructions to form:


```
in a second terminal window, start your 📱 frontend:

cd challenge-0-simple-nft
yarn deploy

in a third terminal window, 🛰 deploy your contract:

cd challenge-0-simple-nft
yarn start
```

to

```

in a second terminal window, 🛰 deploy your contract:

cd challenge-0-simple-nft
yarn deploy

in a thrid terminal window, start your 📱 frontend:

cd challenge-0-simple-nft
yarn start
```

It's a minor change, but i think it's worth making (just started going through the material). I can send in the PR.

**Comment by ZakGriffith** [comment]
Tested this today and was able to do the yarn start before yarn deploy with no errors.  Is this no longer an issue?

**Comment by ZakGriffith** [comment]
After further testing I was wrong, it still breaks if you yarn start first.  Fixed the instructions and closing.

**Pull request closed without merging**
